name: pa_webview_plugin
description: Plugin that allow Flutter to communicate with a native Webview.
authors:
- yyc <yangcheng_vip1@163.com>

homepage: https://github.com/whitekyo/pa_webview_plugin
version: 0.1.0
maintainer: ashawn

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.flutter_webview_plugin
    pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter
